apiVersion: v1
kind: PersistentVolume
metadata:
  name: stock-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ranveer/Documents/Kitematic/k8s/pv/stock"