logging:
  level:
    .: ERROR
    org.springframework: ERROR
    com.ht: INFO
    com.ht.cms.backend.feign: DEBUG
spring:
  profiles:
    active: local
  main:
    banner-mode: console
    allow-bean-definition-overriding: true
  application: 
    name: stock-exchange-service
server:
  port: 9000
management: 
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  health:
    status:
      http-mapping:
          DOWN: 503
          UP: 200  


          

